name: Semgrep Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep
        # Use a verified ruleset identifier from the Semgrep Registry
        run: semgrep --config p/security-audit --config p/cwe-top-25 --error
      - name: Upload Semgrep findings
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-findings
          path: semgrep.log

